import std/[os, strformat, strutils, sequtils]
import ./types
import ./manifest

proc archList(m: Manifest): seq[string] =
  for a in m.workflow.matrixArches:
    result.add $a

proc genGithubWorkflow(m: Manifest): string =
  let arches = archList(m).mapIt("\"" & it & "\"").join(", ")
  result = &"""
# Generated by `zlb ci generate` -- edit distro.hcl's workflow {{ }} block
# and re-run instead of hand-editing the matrix here.
name: Build {m.distro.name}

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  workflow_dispatch: {{}}

jobs:
  build:
    name: build (${{{{ matrix.arch }}}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [{arches}]
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso squashfs-tools grub-pc-bin grub-efi-amd64-bin \
            qemu-user-static binfmt-support gnupg tar

      - name: Install janet
        run: |
          sudo apt-get install -y janet || \
          (curl -fsSL https://janet-lang.org/install.sh | sudo bash)

      - name: Install zlb
        run: |
          curl -fsSL https://github.com/zenith-linux/zlb/releases/latest/download/zlb-linux-x86_64 -o /usr/local/bin/zlb
          chmod +x /usr/local/bin/zlb

      - name: Cache out/cache
        uses: actions/cache@v4
        with:
          path: out/cache
          key: zlb-cache-${{{{ matrix.arch }}}}-${{{{ hashFiles('distro.hcl', 'modules/**') }}}}
          restore-keys: |
            zlb-cache-${{{{ matrix.arch }}}}-

      - name: Import release GPG key
        if: ${{{{ secrets.ZENITH_GPG_PRIVATE_KEY != '' }}}}
        env:
          ZENITH_GPG_PRIVATE_KEY: ${{{{ secrets.ZENITH_GPG_PRIVATE_KEY }}}}
        run: echo "$ZENITH_GPG_PRIVATE_KEY" | gpg --batch --import

      - name: zlb build rootfs
        run: zlb build rootfs --arch ${{{{ matrix.arch }}}}

      - name: zlb build iso
        run: zlb build iso --arch ${{{{ matrix.arch }}}}

      - name: zlb build oci
        run: zlb build oci --arch ${{{{ matrix.arch }}}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: {m.distro.name.toLowerAscii.replace(" ", "-")}-${{{{ matrix.arch }}}}
          path: |
            out/*.iso
            out/*.sha256
            out/*.asc
            out/oci/**
"""

proc genGitlabWorkflow(m: Manifest): string =
  let arches = archList(m)
  var jobs = ""
  for a in arches:
    jobs.add &"""
build:{a}:
  stage: build
  image: ubuntu:24.04
  variables:
    ZLB_ARCH: "{a}"
  cache:
    key: "zlb-cache-{a}"
    paths:
      - out/cache/
  before_script:
    - apt-get update && apt-get install -y xorriso squashfs-tools grub-pc-bin grub-efi-amd64-bin qemu-user-static binfmt-support gnupg tar curl
    - curl -fsSL https://github.com/zenith-linux/zlb/releases/latest/download/zlb-linux-x86_64 -o /usr/local/bin/zlb
    - chmod +x /usr/local/bin/zlb
  script:
    - zlb build rootfs --arch $ZLB_ARCH
    - zlb build iso --arch $ZLB_ARCH
    - zlb build oci --arch $ZLB_ARCH
  artifacts:
    paths:
      - out/*.iso
      - out/*.sha256
      - out/*.asc
      - out/oci/

"""
  result = &"# Generated by `zlb ci generate`\nstages: [build]\n\n" & jobs

proc generateWorkflow*(m: Manifest, projectRoot: string) =
  case m.workflow.provider
  of "gitlab":
    let path = projectRoot / ".gitlab-ci.yml"
    writeFile(path, genGitlabWorkflow(m))
    echo "Wrote " & path
  else:
    let dir = projectRoot / ".github" / "workflows"
    createDir(dir)
    let path = dir / "build.yml"
    writeFile(path, genGithubWorkflow(m))
    echo "Wrote " & path
